name: Frontend Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Generate
        working-directory: ./frontend
        run: npm run generate
        env:
          API_URL: https://api.cubepb.com
          VER: ${{ github.ref }}
          WCA_AUTH_URL: https://worldcubeassociation.org/oauth/authorize?client_id=6rfi-FvIwRXDlPiYzYEUlK5Jt8L6x7ucPZyM-aD8mu0&redirect_uri=https%3A%2F%2Fcubepb.com%2Fwca-redirect&response_type=code&scope=public+email
          WCA_ACCOUNT_MANAGEMENT_URL: https://worldcubeassociation.org/profile/edit
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: "deploy --only hosting:cubepb-65c9e-client"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./frontend
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
